apply plugin: 'com.android.application'

android {
    namespace "com.luckreveal.app"
    compileSdkVersion 35
    defaultConfig {
        applicationId "com.luckreveal.app"
        minSdkVersion 24
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

apply from: 'capacitor.build.gradle'

dependencies {
    implementation project(':capacitor-android')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // JUnit dependency for unit tests
    testImplementation 'junit:junit:4.13.2'
    // AndroidX Test extension for JUnit
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
}
